const ERROR_CODES = Object.freeze({
    CONFLICT : "CONFLICT",
    SERVER_ERROR : "INTERNAL_SERVER_ERROR",
    NOT_FOUND : "NOT_FOUND",
    UNAUTHORIZED : "UNAUTHORIZED"
})

const ERROR_MESSAGES = Object.freeze({
    PRODUCT_ALREADY_EXISTS : "PRODUCT_ALREADY_EXISTS",
    INTERNAL_SERVER_ERROR : "INTERNAL_SERVER_ERROR",
    PRODUCT_NOT_FOUND : "PRODUCT_NOT_FOUND",
    USER_ALREADY_EXISTS : "USER_ALREADY_EXISTS",
    INVALID_USER : "INVALID_CREDENTIALS",
    INVALID_TOKEN : "INVALID_TOKEN",
    NOT_PROVIDED : "TOKEN_NOT_PROVIDED"
})

module.exports = {
    ERROR_CODES,
    ERROR_MESSAGES
}