const VALIDATION_ERROR_CODES = Object.freeze({
    INVALID_TITLE : "INVALID_TITLE_FIELD",
    INVALID_PRICE : "INVALID_PRICE_FIELD",
    INVALID_PUBLISHED : "INVALID_PUBLISHED_FIELD",
    INVALID_USERNAME : "INVALID_USERNAME_FIELD",
    INVALID_PASSWORD : "INVALID_PASSWORD_FIELD",
    INVALID_EMAIL : "INVALID_EMAIL_FIELD",
    INVALID_PHONE : "INVALID_PHONE_FIELD"
})

const VALIDATION_ERROR_MESSAGES = Object.freeze({
    EMPTY_TITLE : "EMPTY_TITLE_FIELD",
    EMPTY_PRICE : "EMPTY_PRICE_FIELD",
    EMPTY_PUBLISHED : "EMPTY_PUBLISHED_FIELD",
    EMPTY_USERNAME : "EMPTY_USERNAME_FIELD",
    EMPTY_PASSWORD : "EMPTY_PASSWORD_FIELD",
    EMPTY_EMAIL : "EMPTY_EMAIL_FIELD",
    EMPTY_PHONE : "EMPTY_PHONE_FIELD"
})

module.exports = {
    VALIDATION_ERROR_CODES,
    VALIDATION_ERROR_MESSAGES
}